openconfig/reference

rpc/openconfig/openconfig.proto
telemetry/collector/cli/query/query.go

This change allows the bytes to be a serialized proto message
If the sender uses this encoding it is up to the receiver to
Understand the schema and properly decode the message.

Add support for PROTO message value type.

---

rpc/openconfig/openconfig.pb.go

This is needed as of grpc/grpc-go@727a60e4 / golang/protobuf@09b5638f.

rpc/openconfig: Upgrade to gRPC API v4.

---

rpc/gnmi/gen.go
rpc/gnmi/gnmi.pb.go

Without this, it's not possible to import this package in gRPC clients/servers, one would have to generate their own stubs instead of working off the upstream package, which is sad.

gNMI: Update the generated Go code and add support for gRPC

---

rpc/gnmi/gen.go
rpc/gnmi/gnmi.pb.go

Because it would be too simple if the generated Go code was alongside the C++ code in https://github.com/google/protobuf/tree/master/src/google/protobuf right?  :)

rpc/gnmi: Fix up the import path for descriptor.proto

---

rpc/gnmi/gnmi-path-conventions.md

* (M) rpc/gnmi/gnmi-path-conventions.md
- Updates specifciation of root path encoding
- Updates wildcard -- change from XPATH // to ...
- Reorganized doc with subheadings

Clarifications and updates to gNMI path specification.

---

rpc/gnoi/gnoi_file.proto

This service allows for simple file operations on the target.

Adding gnoi_file service to the gnoi suite

---

rpc/gnmi/gnmi-extensions.md
rpc/gnmi/gnmi-specification.md

```
* (M) reference/rpc/gnmi/*
- Add specification for extensions to gNMI per the discussion in
#78.
- Add extension fields to the top-level gNMI RPC message payloads.
- Editorial amendments/fixes for technical inaccuracies in the spec.
```
Fixes #78. @aashaikh, @gcsl - PTAL.

Add gNMI extensions specification to reference.

---

rpc/gnmi/mixed-schema.md

```
* (A) reference/gnmi/mixed-schema.md
- Add a reference document covering the use of mixed schema in
gNMI. This covers use of the origin field for multiple schemas
being used within gNMI RPCs.
```

Add a document explaining mixed-schema in gNMI.

---

rpc/gnmi/README.md

Remove the PDF specification link.

---

rpc/gnmi/gnmi-path-strings.md

This PR adds a document which provides a specification for going from a gNMI `Path` message to a string, to ensure that there is a stable reference for implementations.

Add document covering how to represent gNMI paths as strings.

---

rpc/gnmi/gnmi-specification.md

Hi all,
in this PR:
1. Table of contents format is aligned to left
2. Dead links in TOC are removed with the working ones
3. Several internal cross-section links fixed
4. a few html links `<a href>` changed to markdown style `[link](url)`

gNMI specification improvements

---

rpc/gnmi/gnmi-history.md

This change adds the specification for the gNMI History extension. This extension lets clients request historical data.

Add gNMI History extension documentation

---

rpc/gnmi/gnmi-specification.md

```
* (M)rpc/gnmi/gnmi-specification.md
- Update specification to ensure it is clear what type of messages
are bundled according to current proto definition.
```

Clarify Notification bundling in gNMI (credit: wenbli@google.com)

---

rpc/gnmi/gnmi-specification.md

I put this as another paragraph under "The SubscribeResponse Message". Let me know if you'd like this to be in a separate section.
FIXED #145

Clarify that SubscribeResponse messages are not guaranteed to be in timestamp order.

---

rpc/gnmi/gnmi-specification.md

References Decimal64 deprecation document in https://github.com/openconfig/reference/pull/150

Update gNMI proto encoding, remove decimal64

---

rpc/gnmi/gnmi-specification.md

In https://github.com/openconfig/reference/pull/148 we removed path prefixes, this PR updates the heading indexes to account for this change

update heading indexes after path prefixes removal

---

rpc/gnmi/gnmi-specification.md

Added example, and moved around a paragraph to a more related/discoverable place.

Clarify gNMI SetRequest `update` when updating a keyed list.

---

rpc/gnmi/gnmi-specification.md

Also add changelog missed at previous commit.
This follows from the discussion and proposal in https://github.com/openconfig/reference/issues/177.

Add line at top of gNMI spec for gNMI service compatibility

---

rpc/gnmi/gnmi-specification.md

The following replace operation should be invalid since it is really a deletion operation.
Alternatively we allow treating it as a delete, but from the current spec it looks like it would be discouraged and I know of a vendor implementation that also errors out in this case.
```
replace:  {
path:  {
elem:  {
name:  "network-instances"
}
elem:  {
name:  "network-instance"
key:  {
key:  "name"
value:  "RED"
}
}
}
val:  {
json_ietf_val:  "{}"
}
}
```

Clarify that calling replace on a list element with `{}` is invalid.

---

rpc/gnmi/gnmi-union_replace.md

Hi @dplore 
The numbering scheme is not correct, it seems. Let me know if that was not the original intention. 
This PR fixes the numbering to be rendered like this:

Fix numbering scheme in union replace

---

rpc/gnmi/gnmi-commit-confirmed.md

Accompanying PR for https://github.com/openconfig/gnmi/pull/164
/cc @kidiyoor

added set rollback duration documentation

---

rpc/gnmi/gnmi-depth.md

Documentation entry to compliment https://github.com/openconfig/gnmi/pull/166
Rendered doc can be seen [here](https://github.com/openconfig/reference/blob/4ca30e8117b228007ee866b6ca86cc315fa33933/rpc/gnmi/gnmi-depth.md).

gNMI Depth Extension documentation

---

rpc/gnmi/gnmi-specification.md

Added clarity for delete path discussed in gnmi repo issue 145.

gNMI update with explicit deletion

---

rpc/gnmi/gnmi-config-subscriptions.md

Documentation page to complement https://github.com/openconfig/gnmi/pull/169

gNMI config subscription extension documentation
